version: '3.8'
services:
  panstwa-miasta:
    build:
     context: ./
     dockerfile: ./Dockerfile
    environment:
     TZ: "Europe/Warsaw"
     MAX_WORKERS: 1
     WEB_CONCURRENCY: 1
    ports:
     - "5000:80"
    restart: always
